#name: "Pull Request Labeler"
#on:
#  pull_request:
#  push:
#    branches:
#      - main

#jobs:
#  triage:
#    permissions:
#      checks: write
#      contents: read
#      pull-requests: write
#    runs-on: ubuntu-latest
#    steps:
#   - uses: actions/labeler@v4
#      with:
#        repo-token: "${{ secrets.GITHUB_TOKEN }}"
